language: r

sudo: true
cache: 
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false

addons:
  apt:
    packages:
      - libhunspell-dev
      # - hunspell-en-au Wait :-)

packages:
  - magrittr
  - dplyr
  - data.table
  - hunspell
  - testthat
  - devtools
  - grattanReporter

r_github_packages:
  - hughparsonage/grattanReporter

before_install:
  - source ./source/texlive.sh
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  - tlmgr update --all
  - sudo apt-get update
  - sudo apt-get install texlive-bibtex-extra

install: echo Installation step #do not remove this line!

before_script:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    # - wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
    - wget "https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz"
    - tar xzf biber-linux_x86_64.tar.gz
    - export PATH=$PATH:$PWD
    - tlmgr update biber
    - Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
    - Rscript -e 'if (!requireNamespace("grattanReporter", quietly = TRUE)) devtools::install_github("hughparsonage/grattanReporter")'

script: 
  - Rscript -e 'library(grattanReporter);grattanReporter::checkGrattanReport()'
  - pdflatex -draftmode Report.tex
  - biber Report
  - pdflatex -draftmode Report.tex

notifications:
  email: false