language: r
pandoc: false
sudo: true
cache: 
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false

# Switch to binary later for faster compilation
r_packages:
  - devtools
  - data.table
  - magrittr
  - fastmatch
  - stringi
  - Rcpp
  - tibble
  - hms
  - R6
  - BH
  - rlang
  - readr  
  - zoo

r_packages: 
  - clisymbols
  - crayon

addons:
  apt:
    packages:
      - libhunspell-dev
      # - hunspell-en-au Wait :-)
  
r_github_packages:
  - HughParsonage/TeXCheckR
  - HughParsonage/grattanReporter

before_install:
  - source ./travis/texlive.sh
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  - if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then tlmgr install tex-gyre eulervm bold-extra fancyvrb realboxes manfnt lstaddons; fi
  # pdftotext
  - if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then sudo apt-get install poppler-utils; fi
  - tlmgr update --all
  - sudo apt-get update
  - sudo apt-get install texlive-bibtex-extra

install: echo Installation step #do not remove this line!

before_script:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    # - wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
    - wget http://mirrors.ctan.org/biblio/biber/binaries/Linux/biber-linux_x86_64.tar.gz
    - tar xzf biber-linux_x86_64.tar.gz
    - export PATH=$PATH:$PWD
    - tlmgr update biber
    #- Rscript -e 'if (!requireNamespace("hunspell", quietly = TRUE)) system("sudo apt-get install -y r-cran-devtools r-cran-rcpp r-cran-bh r-cran-stringi r-cran-hunspell")'
    - Rscript -e 'install.packages("devtools")'
    - Rscript -e 'devtools::install_github("hughparsonage/hutils")'
    - Rscript -e 'devtools::install_github("hughparsonage/TeXCheckR")'
    - Rscript -e 'devtools::install_github("hughparsonage/grattanReporter")'

script: 
  - set -e
  - for i in *.tex; do pdflatex -interaction=nonstopmode $i > /dev/null 2>&1; done
  - Rscript -e 'library(grattanReporter);checkGrattanReport(compile = TRUE, pre_release = TRUE, .proceed_after_rerun = 3)'
  - if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then Rscript tests/test_grattex.R; fi
  - cd doc
  - if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then Rscript checkDocumentation.R; fi

notifications:
  slack: grattex:7yiVyM6NvMmCE49ccxaUX2QG
  on_success: change
